version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-spring:
    depends_on:
      - mysqldb
    image: gestion-kaddem:1.0
    restart: on-failure
    ports:
      - "8090:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"}'
    stdin_open: true
    tty: true

volumes:
  db: