version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: docker-compose-mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    networks:
      - my-network
    volumes:
      - db:/var/lib/mysql
  spring-boot-app:
    image: semah0500/gestion-kaddem:latest
    container_name: app-back
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-compose-mysql-db:3306/kaddem?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - my-network
    restart: always

networks:
  my-network:

volumes:
  db :